Skip to content
 
Search or jump to…

Pull requests
Issues
Marketplace
Explore
 @therealvenenoiot
Sign out
We are having a problem billing the 1010101012101 organization. Please update your payment method or call your payment provider for details on why the transaction failed. If you don’t need access to your private repositories, you can downgrade to the Free plan.
You can always contact support with any questions.
@1010101012101	
1010101012101
 Repositories 280  People 1  Teams 0  Projects 0  Settings

Find a repository…
 	
Orbit-Theme
Forked from therealvenenoiot/Orbit-Theme
FREE Bootstrap 4 Resume/CV Template for Developers -
 CSS  270 Updated 2 minutes ago
libphonenumber-csharp
Forked from twcclegg/libphonenumber-csharp
Offical C# port of https://github.com/googlei18n/libphonenumber
 C++  58 Apache-2.0 Updated 4 minutes ago
terraform-azurerm-compute
Forked from therealvenenoiot/terraform-azurerm-compute
Terraform Azure RM Compute Module
 HCL  65 MIT Updated 27 minutes ago
Aminer-Trend-Graph
Forked from JingqingZ/Aminer-Trend-Graph
Uses docker compose to build up an entire kinetic environment and seed it with test data
 Python  1 Updated an hour ago
docker-kinetic-platform
Forked from therealvenenoiot/docker-kinetic-platform
Uses docker compose to build up an entire kinetic environment and seed it with test data
 Shell  4 Updated 3 hours ago
arestech.io
Forked from therealvenenoiot/arestech.io
Website of Ares Tech GmbH
 JavaScript  4 LGPL-3.0 Updated 3 hours ago
griddb_nosql
Forked from griddb/griddb_nosql
high performance, high scalability and high reliability database for IoT & big data
 C++  722 Updated 4 hours ago
btcpayserverslackbot
Forked from btcpayserver/btcpayserverslackbot
Provides helper scripts for inferring xlink local ancestry, performing ancestry-specific PCA, etc
 C#  2 Updated 6 days ago
Xero-Net
Forked from therealvenenoiot/Xero-Net
A skinny wrapper of the Xero API. Supports Payroll, Accounting & Files
 C#  173 Updated 6 days ago
log.txt
Forked from therealvenenoiot/log.txt
keep track of my text files
 Io  2 Updated 7 days ago
pascal-programs
Forked from therealvenenoiot/pascal-programs
1001010101111010102010110110&#cdndnsdbsfbgbbdbdbsbdbdbsbsbsbsbsbdbdbbsbdbd
 C  2 Updated 7 days ago
weedmaps-cli
Forked from Pholey/weedmaps-cli
PHP 7 Migration Assistant Report (MAR)
 JavaScript  3 Updated 7 days ago
instanttransmission
Forked from therealvenenoiot/instanttransmission
A tiny JavaScript debugging utility modelled after Node.js core's debugging technique. Works in Node.js and web browsers
 DIGITAL Command Language  2 MPL-2.0 Updated 7 days ago
ark
Forked from therealvenenoiot/ark
Heptio Ark is a utility for managing disaster recovery, specifically for your Kubernetes cluster resources and persistent volumes. Brought to you by Heptio.
 Go  319 Apache-2.0 Updated 7 days ago
Web-Performance-and-Compatibility-Lab
Forked from therealvenenoiot/Web-Performance-and-Compatibility-Lab
A lab for checking and fixing modern web interoperability and performance issues on a simple front-end website
 HTML  27 Updated 7 days ago
ENEL-453-Labs
Forked from therealvenenoiot/ENEL-453-Labs
Lab documents and project code for ENEL 453 at the Schulich School of Engineering
 C  3 Updated 7 days ago
homemade-machine-learning
Forked from therealvenenoiot/homemade-machine-learning
robot Python examples of popular machine learning algorithms with interactive Jupyter demos and math being explained
 Jupyter Notebook  1,767 MIT Updated 7 days ago
therealcurlsport
Forked from therealvenenoiot/therealcurlsport
Oscarg933
 Brainfuck  1 MPL-2.0 Updated 7 days ago
python-django-cd-sample
Forked from therealvenenoiot/python-django-cd-sample
Continous Delivery Sample
 Python  54 Updated 7 days ago
weedmaps-python-parser
Forked from dharmagetic/weedmaps-python-parser
Parse information of Organisations from Googlemaps and Weedmaps. Write parsed info to XLSX file.
 Python  2 Apache-2.0 Updated 7 days ago
https-oscarg933.github-io Private
Forked from therealvenenoiot/https-oscarg933.github-io
Raspberry Pi Powered Chatbot
 1 Updated 7 days ago
newman
Forked from postmanlabs/newman
Newman is a command-line collection runner for Postman
 JavaScript  486 Apache-2.0 Updated 8 days ago
facebook.git.yml
Forked from therealvenenoiot/facebook.git.yml
A tiny JavaScript debugging utility modelled after Node.js core's debugging technique. Works in Node.js and web browsers
 JavaScript  1 Updated 8 days ago
csdocs
Forked from sanjosh/csdocs
Docs and Notes on various systems or concepts
 HTML  3 Apache-2.0 Updated 8 days ago
domotique_bts_sn_ec_projet
Forked from DrBalf/domotique_bts_sn_ec_projet
projet d'épreuve final pour le bts système numérique, option : Electronique et communication
 HTML  3 Updated 20 days ago
ezTime
Forked from ropg/ezTime
ezTime — pronounced "Easy Time" — is a very easy to use Arduino time and date library that provides NTP network time lookups, extensive timezone support, formatted time and date strings, user events, millisecond precision and more.
 C++  10 MIT Updated 24 days ago
jargonfile
Forked from Jargonfile/jargonfile
Jargon File
 HTML  7 GPL-3.0 Updated 24 days ago
falknews1268.github.io
Forked from falknews1268/falknews1268.github.io
Quantum core real-time Jenkins react plug-in
 HTML  1 Updated 24 days ago
Cmpe547_Final_Project
Forked from yigitozgumus/Cmpe547_Final_Project
Rakuten MA - morphological analyzer (word segmentor + PoS Tagger) for Chinese and Japanese written purely in JavaScript.
 Jupyter Notebook  4 MIT Updated 24 days ago
Webscrape_dice
Forked from umeshdhanwal/Webscrape_dice
its used for scraping the website https://www.dice.com/skills/browse
 Python  1 Updated 24 days ago
Top languages
 JavaScript   Python   Java  HTML   C++
1 
People
@therealvenenoiot
therealvenenoiot
Oscar gomez
© 2019 GitHub, Inc.
Terms
Privacy
Security
Status
Help
Contact GitHub
Pricing
API
Training
Blog
About
Press h to open a hovercard with more details.
